=== oshToy/Character-Aware-LM/json_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "logs_folder": {
      "type": "string"
    },
    "data_sets_folder": {
      "type": "string"
    },
    "trained_models_folder": {
      "type": "string"
    },

    "models": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "data_set": {
              "type": "string"
            },
            "training": {
              "type": "boolean"
            },
             "testing": {
              "type": "boolean"
            },
            "checkpoint_number_for_train_or_null_for_last_checkpoint": {
              "type": ["integer", "null"]
            },

            "checkpoint_file_for_test": {
              "type": ["string", "null"]
            },
            "embedding": {
              "type": "string",
              "default": "kim fasttext"
            },
            "fasttext_model_path": {
              "type": "string"
            },
            "max_epochs": {
              "type": "integer",
              "default": 25
            },
            "rnn_size": {
              "type": "integer",
              "default": 650
            },
            "rnn_layers": {
              "type": "integer",
              "default": 1
            },
            "highway_layers": {
              "type": "integer",
              "default": 2
            }
          },
          "required": [
            "data_set",
            "training",
            "testing",
            "checkpoint_number_for_test_or_null_for_last_checkpoint",
            "checkpoint_file_for_test",
            "embedding",
            "fasttext_model_path",
            "max_epochs",
            "rnn_size",
            "rnn_layers",
            "highway_layers"
          ]
        }
      ]
    }
  },
  "required": [
    "logs_folder",
    "data_sets_folder",
    "trained_models_folder",
    "models"
  ]
}

=== oshToy/Character-Aware-LM/config.json
{
"logs_folder":"./logs/",
"data_sets_folder":"./data_sets",
"trained_models_folder":"./trained_models",
"models":
[
 {
  "data_set": "AMI",
  "training": true,
  "testing": false,
  "checkpoint_number_for_test_or_null_for_last_checkpoint": null,
  "checkpoint_file_for_test": null,
  "embedding":"kim fasttext",
  "fasttext_model_path": "E:\\RNNLM Project\\Models\\Wikipedia\\Lower Case\\15 Epoch\\Wikipedia_epoch15.model",
  "max_epochs": 1,
  "rnn_size": 650,
  "rnn_layers": 1,
  "highway_layers": 2
 },
 {
  "data_set": "AMI",
  "training": true,
  "testing": false,
  "checkpoint_number_for_test_or_null_for_last_checkpoint": null,
  "checkpoint_file_for_test": null,
  "embedding":"kim fasttext",
  "fasttext_model_path": "E:\\RNNLM Project\\Models\\Wikipedia\\Lower Case\\15 Epoch\\Wikipedia_epoch15.model",
  "max_epochs": 2,
  "rnn_size": 650,
  "rnn_layers": 1,
  "highway_layers": 2
 }
]
}
